#!/usr/bin/env node
// gen-tracker.js — Auto-generate composition-tracker.md from page-manifest.json
//
// Phase 5 of the unified manifest plan. Reads the manifest produced by
// scan-source.js and writes a structured Markdown tracker.
//
// Usage:
//   node scripts/gen-tracker.js              Generate inventory/composition-tracker.md
//   node scripts/gen-tracker.js --dry-run    Print to stdout instead of writing

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const MANIFEST = join(ROOT, 'references', 'page-manifest.json');
const OUTPUT = join(ROOT, 'inventory', 'composition-tracker.md');

// ─── CLI ────────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');

// ─── Helpers ────────────────────────────────────────────────────────────────

function check(val) {
  return val ? '✓' : '✗';
}

function pct(n, total) {
  if (total === 0) return '0%';
  return `${Math.round((n / total) * 100)}%`;
}

/** Pad a string to a fixed width for table alignment */
function pad(str, width) {
  return String(str).padEnd(width);
}

// ─── Main ───────────────────────────────────────────────────────────────────

function main() {
  // Validate manifest exists
  if (!existsSync(MANIFEST)) {
    console.error(`Error: page-manifest.json not found at ${MANIFEST}`);
    console.error('Run "npm run scan:source" first to generate the manifest.');
    process.exit(1);
  }

  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
  const allPages = manifest.pages;

  // Filter to routed pages only
  const routed = allPages.filter(p => p.source.routePath);

  // Sort: section (nulls last), then name
  routed.sort((a, b) => {
    const aSec = a.section || 'zzz';
    const bSec = b.section || 'zzz';
    if (aSec !== bSec) return aSec.localeCompare(bSec);
    return a.name.localeCompare(b.name);
  });

  // ─── Compute statistics ─────────────────────────────────────────────────

  const total = routed.length;
  const classified = routed.filter(p => p.layout.type !== 'UNKNOWN').length;
  const withBrief = routed.filter(p => p.figmaPrototype.briefFile).length;
  const withPrototype = routed.filter(p => p.codedPrototype.prototypeFile).length;
  const highConfidence = routed.filter(p => p.layout.confidence >= 0.8).length;

  // ─── Layout type breakdown ──────────────────────────────────────────────

  const layoutMap = new Map(); // type → { count, withBrief, withPrototype, example }
  for (const p of routed) {
    const t = p.layout.type;
    if (!layoutMap.has(t)) {
      layoutMap.set(t, { count: 0, withBrief: 0, withPrototype: 0, example: null });
    }
    const entry = layoutMap.get(t);
    entry.count++;
    if (p.figmaPrototype.briefFile) entry.withBrief++;
    if (p.codedPrototype.prototypeFile) entry.withPrototype++;
    if (!entry.example) entry.example = p.id;
  }

  // Sort layout types by count descending
  const layoutTypes = [...layoutMap.entries()].sort((a, b) => b[1].count - a[1].count);

  // ─── Section breakdown ──────────────────────────────────────────────────

  const sectionMap = new Map(); // section → count
  for (const p of routed) {
    const sec = p.section || 'Unclassified';
    sectionMap.set(sec, (sectionMap.get(sec) || 0) + 1);
  }

  // ─── Build Markdown ─────────────────────────────────────────────────────

  const lines = [];
  const now = new Date().toISOString().split('T')[0];

  lines.push('# Composition Tracker');
  lines.push('');
  lines.push(`> Auto-generated by \`npm run gen:tracker\` from page-manifest.json on ${now}.`);
  lines.push('> Do not edit manually — changes will be overwritten on next run.');
  lines.push('');

  // ─── Summary table ──────────────────────────────────────────────────────

  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Total routed pages | ${total} |`);
  lines.push(`| Layout classified | ${classified}/${total} (${pct(classified, total)}) |`);
  lines.push(`| With Figma brief | ${withBrief} |`);
  lines.push(`| With coded prototype | ${withPrototype} |`);
  lines.push(`| High confidence (≥0.8) | ${highConfidence} |`);
  lines.push('');

  // ─── Section breakdown ──────────────────────────────────────────────────

  lines.push('## Section Breakdown');
  lines.push('');
  lines.push('| Section | Pages |');
  lines.push('|---------|-------|');
  for (const [sec, count] of [...sectionMap.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${sec} | ${count} |`);
  }
  lines.push('');

  // ─── Layout type coverage ───────────────────────────────────────────────

  lines.push('## Layout Type Coverage');
  lines.push('');
  lines.push('| Layout | Count | With Brief | With Prototype | Example |');
  lines.push('|--------|-------|------------|----------------|---------|');
  for (const [type, data] of layoutTypes) {
    lines.push(`| ${type} | ${data.count} | ${data.withBrief} | ${data.withPrototype} | ${data.example} |`);
  }
  lines.push('');

  // ─── All routed pages table ─────────────────────────────────────────────

  lines.push('## All Routed Pages');
  lines.push('');
  lines.push('| # | Page | Section | Layout | Confidence | Brief | Prototype | Complexity |');
  lines.push('|---|------|---------|--------|------------|-------|-----------|------------|');

  let idx = 0;
  for (const p of routed) {
    idx++;
    const hasBrief = check(p.figmaPrototype.briefFile);
    const hasProto = check(p.codedPrototype.prototypeFile);
    const conf = p.layout.confidence.toFixed(2);
    const section = p.section || '—';
    const complexity = p.codedPrototype.complexity || '—';

    lines.push(`| ${idx} | ${p.name} | ${section} | ${p.layout.type} | ${conf} | ${hasBrief} | ${hasProto} | ${complexity} |`);
  }

  lines.push('');

  // ─── Usage instructions ─────────────────────────────────────────────────

  lines.push('---');
  lines.push('');
  lines.push('## Usage');
  lines.push('');
  lines.push('```bash');
  lines.push('# Regenerate this file from the latest manifest');
  lines.push('npm run gen:tracker');
  lines.push('');
  lines.push('# Preview without writing (prints to stdout)');
  lines.push('node scripts/gen-tracker.js --dry-run');
  lines.push('');
  lines.push('# Update the manifest first, then regenerate');
  lines.push('npm run scan:source && npm run gen:tracker');
  lines.push('```');
  lines.push('');
  lines.push('**Source:** `references/page-manifest.json` (generated by `npm run scan:source`)');
  lines.push('');
  lines.push('**Columns:**');
  lines.push('- **Page** — Human-readable name from scan manifest or Vue filename');
  lines.push('- **Section** — Platform navigation section (CRM, Singularity, etc.)');
  lines.push('- **Layout** — Classified layout type (LIST-SIMPLE, FORM, DASH, etc.)');
  lines.push('- **Confidence** — Layout classification confidence (0.0–1.0)');
  lines.push('- **Brief** — ✓ if a Figma prototype brief exists in `skills/prototype-generator/briefs/`');
  lines.push('- **Prototype** — ✓ if a coded prototype `.vue` file exists');
  lines.push('- **Complexity** — Estimated build complexity (low/medium/high)');
  lines.push('');

  // ─── Output ─────────────────────────────────────────────────────────────

  const content = lines.join('\n');

  if (dryRun) {
    console.log(content);
  } else {
    writeFileSync(OUTPUT, content);
    console.log(`Composition tracker generated → ${relative(process.cwd(), OUTPUT)}`);
    console.log(`  ${total} routed pages, ${layoutTypes.length} layout types`);
    console.log(`  ${withBrief} with briefs, ${withPrototype} with prototypes`);
  }
}

main();
